In [1]:
from eaaw_graphlime_utils import *
import gc

import seaborn as sns
import seaborn.objects as so


from   pcgrad.pcgrad import PCGrad # from the following: https://github.com/WeiChengTseng/Pytorch-PCGrad. Renamed to 'pcgrad' and moved to site-packages folder.

import pandas as pd

# torch.manual_seed(2)

ScalarFunction


In [2]:
dataset_name='computers'
if dataset_attributes[dataset_name]['single_or_multi_graph']=='single':
    dataset = prep_data(dataset_name=dataset_name, location='default', batch_size='default', transform_list='default',
                        train_val_test_split=[0.9,0.05,0.05])
    graph_to_watermark = data = dataset[0]
elif dataset_attributes[dataset_name]['single_or_multi_graph']=='multi':
    [train_dataset, val_dataset, test_dataset], [train_loader, val_loader, test_loader] = prep_data(dataset_name=dataset_name, location='default', 
                                                                                                    batch_size='default', transform_list='default',
                                                                                                                            train_val_test_split=[0.9,0.05,0.05])
    graph_to_watermark = train_dataset[0]

Transorms used when loading computers: ['CreateMaskTransform()']
train_mask: 12376
test_mask: 689
val_mask: 687


In [10]:
#optimization_kwargs, node_classifier_kwargs, watermark_kwargs, subgraph_kwargs, augment_kwargs, watermark_loss_kwargs, regression_kwargs = get_presets(dataset, 'default')
get_presets(dataset,dataset_name)

compare_unimportant_against_random=False

config.node_classifier_kwargs['dropout']=0
config.node_classifier_kwargs['dropout_subgraphs']=0
config.watermark_kwargs['fancy_selection_kwargs']['clf_only_epochs'] = 20
config.optimization_kwargs['lr']=0.001
config.optimization_kwargs['epochs']=100
# config.optimization_kwargs['coefWmk']=300
config.optimization_kwargs['perturb_x']=False
config.optimization_kwargs['perturb_lr']=1e3

config.optimization_kwargs['coefWmk_kwargs']= {
                                                'coefWmk':50,
                                                'schedule_coef_wmk': False,
                                                'min_coefWmk_scheduled': 100,
                                                'reach_max_coef_wmk_by_epoch':70,
                                                }

config.optimization_kwargs['use_pcgrad']=True
config.optimization_kwargs['use_sam']=False
config.optimization_kwargs['sam_momentum']=0.5
config.optimization_kwargs['sam_rho']=1e-5


config.optimization_kwargs['use_gradnorm']=False


config.augment_kwargs['nodeDrop']['use']=False
config.augment_kwargs['nodeMixUp']['use']=True
config.augment_kwargs['nodeFeatMask']['use']=False
config.augment_kwargs['edgeDrop']['use']=False
config.augment_kwargs['separate_trainset_from_subgraphs'] = True
config.augment_kwargs['ignore_subgraphs'] = True
config.watermark_kwargs['fancy_selection_kwargs']['percent_of_features_to_watermark']=3
config.watermark_kwargs['watermark_type']='fancy'
config.subgraph_kwargs['numSubgraphs']=2
config.subgraph_kwargs['fraction']=0.03
config.subgraph_kwargs['method']='random'
config.optimization_kwargs['sacrifice_kwargs']['method']='subgraph_node_indices'
config.optimization_kwargs['sacrifice_kwargs']['percentage']=1
config.optimization_kwargs['separate_forward_passes_per_subgraph']=False
config.optimization_kwargs['clf_only']=False
config.watermark_loss_kwargs['epsilon']=1e-1

config.regression_kwargs['lambda']=1e-3

validate_kwargs()


In [11]:
merged_dict = merge_kwargs_dicts()#config.node_classifier_kwargs, config.optimization_kwargs, config.watermark_kwargs, config.subgraph_kwargs, config.regression_kwargs, config.watermark_loss_kwargs, config.augment_kwargs)
merged_dict_keys = list(merged_dict.keys()) + ['Train Acc','Val Acc','Match Rates','Final Betas','watermark']
all_dfs = pd.DataFrame(dict(zip(merged_dict_keys,[]*len(merged_dict_keys))))

# all_dfs = pickle.load(open('/Users/janedowner/Desktop/Desktop/IDEAL/Project_2/src/results_df.pkl','rb'))
# all_results = {}



scale_beta_method=None
debug_multiple_subgraphs=False



In [12]:
Trainer_ = Trainer(data, dataset_name)
Trainer_.x, Trainer_.edge_index = data.x, data.edge_index
Trainer_.test_perturb_x()

setup_subgraph_dict
enumerate_over_me: range(0, 2)
Before generate_subgraph: numHops = 1
selected_nodes: tensor([12012,  8021,   737,  7827, 13159,  5281,  8485,  9473,   187, 11318,
         5833, 13655,  4809,  3782,  1535,  9369, 12133,  7504,  2329,  7787,
         3546,    58,  5216,  1446,  6366,  6471, 13721, 10245,  9393,  9373,
         8182,  6887, 12138,  5169,  2462,  8599,  8713, 13281,  5905,  8355,
        11951,  1545,  3214,   143, 12011,  2527, 12911,   735,  5807,  1746,
         7920, 10924, 13554, 13218,   264,  5378,  1506,  5210,  2162, 12674,
         2086,  2658,  2555,  5487,  4242, 13236,  1727,  4923,  9026,  6087,
         7139, 10042, 10132,  9392, 11561, 11306,  2509,  3744, 13705, 10014,
         8011,  8736,  4558,  6143,  6897,  6658, 11578,   640,    10,  3591,
         8994,  3587,  8691,  4183,  9662,  7036,  2849,  5751,  9853, 11301,
         4824, 12411, 12414, 11503,  1669, 12887,  5262,  3286,  8179,  6906,
         6602,  9349,  1492,   396,  

KeyboardInterrupt: 

In [6]:

# for _ in range(3):
# for mom in [1e-3, 1e-2, 1e-1, 0.5]:
#     for rho in [1e-7,1e-5,1e-3]:
# config.optimization_kwargs['sam_momentum'] = mom
# config.optimization_kwargs['sam_rho'] = rho
# for i in range(10):
#     if i<5:
#         config.optimization_kwargs['use_sam']=True
#         title = f'With SAM - momentum={np.round(config.optimization_kwargs['sam_momentum'],3)}, rho={config.optimization_kwargs['sam_rho']}'
#     else:
# config.optimization_kwargs['use_sam']=False
for _ in range(1):
    config.optimization_kwargs['perturb_x']=True
    title = f'Perturb X'
    Trainer_ = Trainer(data, dataset_name)
    node_classifier, history, subgraph_dict, \
    all_feature_importances, all_watermark_indices, probas = Trainer_.train(debug_multiple_subgraphs=False, save=True, print_every=1)

    primary_loss_curve, watermark_loss_curve, final_betas, watermarks, \
    percent_matches, percent_match_mean, percent_match_std, \
        primary_acc_curve, watermark_acc_curve, train_acc, val_acc = get_performance_trends(history, subgraph_dict)
    final_plot(history, title, percent_matches, primary_loss_curve, watermark_loss_curve, train_acc)  
for _ in range(1):
    config.optimization_kwargs['perturb_x']=False
    title = f'Vanilla'
    Trainer_ = Trainer(data, dataset_name)
    node_classifier, history, subgraph_dict, \
    all_feature_importances, all_watermark_indices, probas = Trainer_.train(debug_multiple_subgraphs=False, save=True, print_every=1)

    primary_loss_curve, watermark_loss_curve, final_betas, watermarks, \
    percent_matches, percent_match_mean, percent_match_std, \
        primary_acc_curve, watermark_acc_curve, train_acc, val_acc = get_performance_trends(history, subgraph_dict)
    final_plot(history, title, percent_matches, primary_loss_curve, watermark_loss_curve, train_acc)  
for _ in range(1):
    config.optimization_kwargs['separate_forward_passes_per_subgraph']=True
    title = f'Separate Forward Passes for D_trn and D_wmk'
    Trainer_ = Trainer(data, dataset_name)
    node_classifier, history, subgraph_dict, \
    all_feature_importances, all_watermark_indices, probas = Trainer_.train(debug_multiple_subgraphs=False, save=True, print_every=1)

    primary_loss_curve, watermark_loss_curve, final_betas, watermarks, \
    percent_matches, percent_match_mean, percent_match_std, \
        primary_acc_curve, watermark_acc_curve, train_acc, val_acc = get_performance_trends(history, subgraph_dict)
    final_plot(history, title, percent_matches, primary_loss_curve, watermark_loss_curve, train_acc)  

setup_subgraph_dict
nodeIndices: [3941, 10762, 7971, 10573, 12294, 9009, 2051, 7184, 12412, 3009, 8366, 11870, 8078, 4310, 1436, 5810, 5176, 63, 5480, 3341, 3391, 3471, 10484, 13199, 271, 8673, 4218, 7932, 4076, 77, 3494, 12140, 12368, 8868, 7950, 828, 10143, 3512, 4907, 6076, 11597, 7539, 3852, 10297, 2495, 2228, 1059, 5460, 10440, 6053, 13425, 5291, 5392]
nodeIndices: [10420, 6468, 7324, 12547, 2648, 2352, 6451, 8998, 12179, 4946, 10235, 9702, 7397, 7543, 13192, 6969, 13118, 2503, 7228, 4760, 4088, 11662, 2083, 4610, 9324, 10388, 6961, 11461, 2921, 7085, 4745, 12816, 8528, 13447, 9648, 7067, 8270, 10815, 12520, 9413, 4964, 2868, 2400, 11572, 204, 12844, 9258, 4512, 12080, 2056, 404, 10371, 10955]
nodeIndices: [3846, 12387, 10313, 6170, 9120, 11052, 11328, 3261, 694, 2515, 8044, 9323, 4843, 3838, 5289, 8344, 7747, 6051, 10242, 197, 8988, 359, 13407, 11363, 7318, 9849, 638, 802, 3091, 9023, 11745, 5595, 9287, 1080, 9358, 2420, 11009, 1284, 3787, 12090, 2164, 3720, 6824, 1604, 6672, 136

  0%|          | 0/100 [00:00<?, ?it/s]

backward
Epoch:   0, loss_primary = 4.922, loss_watermark = n/a, B*W = n/a, train acc = 0.093, val acc = 0.098
backward
Epoch:   1, loss_primary = 2.677, loss_watermark = n/a, B*W = n/a, train acc = 0.429, val acc = 0.418
backward


KeyboardInterrupt: 

In [ ]:
tensor_xavier = torch.empty(data.x.shape)
torch.nn.init.xavier_uniform_(tensor_xavier,gain=1e-2)

tensor([[ 7.3974e-05,  2.4820e-05, -3.4065e-05,  ...,  1.6329e-05,
         -1.0969e-04,  1.1011e-04],
        [ 1.0220e-04,  1.8559e-04, -2.0203e-04,  ...,  1.3876e-04,
          8.2197e-05,  1.9596e-04],
        [ 1.0750e-04,  1.9901e-04,  7.0682e-05,  ..., -1.0800e-04,
         -2.3513e-05, -1.5672e-04],
        ...,
        [-1.7689e-04, -6.4846e-05, -1.4152e-04,  ..., -2.6652e-05,
          2.0227e-04,  1.3177e-04],
        [-1.7342e-04, -5.4438e-06, -1.7486e-04,  ..., -7.9367e-05,
          1.9433e-05,  1.0149e-06],
        [ 1.9578e-04, -1.2511e-04, -6.7696e-05,  ..., -5.9879e-05,
          1.2705e-04,  2.8181e-07]])

In [ ]:
Trainer_.x[torch.tensor(list(set(np.concatenate(Trainer_.all_watermark_indices))))]

tensor([[ 40.,   0.,   0.,  ...,   1.,  40.,   0.],
        [-39., -39.,   0.,  ..., -39.,   0., -39.],
        [  1.,   1., -39.,  ...,   1.,   1.,   1.],
        ...,
        [-39.,  40.,   0.,  ...,   0.,   0.,  40.],
        [-39.,   0., -39.,  ...,   0., -39.,   1.],
        [  0.,   0.,   0.,  ...,   0., -39.,   1.]], grad_fn=<IndexBackward0>)

In [ ]:
config.node_classifier_kwargs.keys()

dict_keys(['arch', 'activation', 'nLayers', 'hDim', 'dropout', 'dropout_subgraphs', 'skip_connections', 'heads_1', 'heads_2', 'inDim', 'outDim'])

In [ ]:

''' (individualize boolean, multisubgraph method, index selection method) '''
selection_kwargss = [#(False, None, 'random'), # random, not individualized
                    (False,'average','unimportant'), # average, not individualized
                    #(False,'concat','unimportant'), # concat, not inividualized
                    # (True,None,'unimportant') # unimportant, individualized
                    ]

''' (method, regenerate_boolean) '''
subgraph_methods = [('random',False)]

''' [subset, percentage] '''
sacrifice_kwargss = [['train_node_indices',1],['train_node_indices',0.75],['subgraph_node_indices',1],[None,None]]

''' (method, L2_lambda (if applicable, else None) '''
regularization_kwargs = [(None,None),('L2',0.01),('beta_var',None)]


variables = {'augment': [{'separate_trainset_from_subgraphs': True,
                          'ignore_subgraphs': True,
                          'nodeDrop': False,
                          'nodeMixUp': False,
                          'nodeFeatMask': False,
                          'edgeDrop': False},
                          {'separate_trainset_from_subgraphs': True,
                          'ignore_subgraphs': True,
                          'nodeDrop': True,
                          'nodeMixUp': True,
                          'nodeFeatMask': True,
                          'edgeDrop': True},],
             'sacrifice_kwargs':  sacrifice_kwargss,
             'beta_selection': selection_kwargss,
             'use_PCgrad': [True,False],
             'subgraph_method': subgraph_methods,
             'reg': regularization_kwargs,
             'perc': [3],
             'clf_epochs': [10,20],
             'coef_wmk': [200,600],
             'frac': [0.02],
             'num_subgraphs': [2,7],
             'balance_beta_weights': [True,False],
             'ignore_subgraph_neighbors': [True, False]}




# config.optimization_kwargs['clf_only']=False       
# watermarking_order = ['augment','use_PCgrad','sacrifice_kwargs','beta_selection','subgraph_method','reg','perc','clf_epochs','frac','coef_wmk','num_subgraphs','balance_beta_weights','ignore_subgraph_neighbors']
# print("watermarking:", watermarking_order)
# count, [node_classifier, history, subgraph_dict,\
#          all_feature_importances, all_watermark_indices, probas] = dynamic_grid_search(data, dataset_name, debug_multiple_subgraphs, 
#                                                                                        all_dfs, False, variables, watermarking_order,
#                                                                                        count_only=True)
# print(count)


config.augment_kwargs['separate_trainset_from_subgraphs'] = True
config.augment_kwargs['ignore_subgraphs'] = True
perturb=False
perturb_lr = 1e-3
node_classifier, history, subgraph_dict, \
    all_feature_importances, all_watermark_indices, probas = train(data, dataset_name, debug_multiple_subgraphs=False, save=True, print_every=1,perturb=perturb,perturb_lr=perturb_lr)
primary_loss_curve, watermark_loss_curve, final_betas, watermarks, \
    percent_matches, percent_match_mean, percent_match_std, \
        primary_acc_curve, watermark_acc_curve, train_acc, val_acc = get_performance_trends(history, subgraph_dict)
final_plot(history, '', percent_matches, primary_loss_curve, watermark_loss_curve, train_acc)  



NameError: name 'train' is not defined

In [ ]:
data.x[all]

IndexError: only integers, slices (`:`), ellipsis (`...`), None and long or byte Variables are valid indices (got builtin_function_or_method)

In [ ]:
folder = '/Users/janedowner/Desktop/Desktop/IDEAL/Project_2/training_results/computers/archGCN_elu_nLayers3_hDim256_drop0_skipTrue/_3%UnimportantIndices_average_10ClfEpochs_random_fraction0.01_numSubgraphs10_eps0.1_raw_beta_nodeMixUp40_lr0.002_epochs80_coefWmk200_regressionLambda0.1'
probas = pickle.load(open(f'{folder}/probas','rb'))
subgraph_dict = pickle.load(open(f'{folder}/subgraph_dict','rb'))
all_watermark_indices = pickle.load(open(f'{folder}/all_watermark_indices','rb'))
node_classifier = pickle.load(open(f'{folder}/node_classifier','rb'))
history = pickle.load(open(f'{folder}/history','rb'))


In [ ]:
data

NameError: name 'data' is not defined

In [ ]:
import nlopt
import numpy as np

# Define your objective function
def objective(x, grad):
    if grad.size > 0:
        # Compute gradient if needed
        x_tensor = torch.tensor(x, dtype=torch.float32).reshape(original_shape)
        x_tensor.requires_grad = True
        log_logits_sub = node_classifier(x_tensor, edge_index)
        probas_sub = log_logits_sub.clone().exp()

        omit_indices, not_omit_indices = get_omit_indices(x_tensor, this_watermark, ignore_zeros_from_subgraphs=False)
        raw_beta = solve_regression(x_tensor, probas_sub, regression_kwargs['lambda'])
        beta = process_beta(raw_beta, watermark_loss_kwargs['alpha'], omit_indices, watermark_loss_kwargs['scale_beta_method'])
        B_x_W = (beta * this_watermark).clone()
        B_x_W = B_x_W[not_omit_indices]
        balanced_beta_weights = torch.ones_like(B_x_W)
        balanced_beta_weights = balanced_beta_weights[not_omit_indices]
        loss = torch.mean(torch.clamp(watermark_loss_kwargs['epsilon'] - B_x_W, min=0) * balanced_beta_weights)
        loss.backward()

        grad[:] = x_tensor.grad.numpy().flatten()

    return loss.item()

ModuleNotFoundError: No module named 'nlopt'

In [ ]:

from scipy.optimize import minimize
results = []
for sig in subgraph_dict.keys():
    watermark_loss_kwargs = config.watermark_loss_kwargs
    regression_kwargs = config.regression_kwargs
    this_watermark, data_sub, subgraph_node_indices = [subgraph_dict[sig][k] for k in ['watermark','subgraph','nodeIndices']]
    x_sub = data_sub.x
    edge_index = data_sub.edge_index
    original_shape = x_sub.shape
    x_sub_flat = x_sub.flatten()
    # global i
    # i = 0
    def compute_watermark_loss(x_sub_flat):
        # global i
        # i+=1
        # print(/i,end='\r')
        # print('hi')
        x_sub = torch.tensor(x_sub_flat, dtype=torch.float32).reshape(original_shape)
        balanced_beta_weights = torch.ones(x_sub.shape[1])

        log_logits_sub = node_classifier(x_sub, edge_index)
        probas_sub = log_logits_sub.clone().exp()


        omit_indices,not_omit_indices = get_omit_indices(x_sub, this_watermark,ignore_zeros_from_subgraphs=False) #indices where watermark is 0
        raw_beta            = solve_regression(x_sub, probas_sub, regression_kwargs['lambda'])
        beta                = process_beta(raw_beta, watermark_loss_kwargs['alpha'], omit_indices, watermark_loss_kwargs['scale_beta_method'])
        B_x_W = (beta*this_watermark).clone()
        B_x_W = B_x_W[not_omit_indices]
        balanced_beta_weights = balanced_beta_weights[not_omit_indices]
        this_loss_watermark = torch.mean(torch.clamp(watermark_loss_kwargs['epsilon']-B_x_W, min=0)*balanced_beta_weights)
        loss_watermark  = this_loss_watermark
        # print('ok')
        return loss_watermark.item()

    # Ensure maxiter is enforced and debugging output
    options = {'maxfun': 2, 'iprint':110, 'maxls':2, 'maxiter':2}

    # Use the L-BFGS-B algorithm for optimization
    result = minimize(compute_watermark_loss, x_sub_flat, 
                      method='L-BFGS-B', 
                      options=options)

    # The optimal x found by the optimizer
    results.append(result)
    # print(result)


_minimize_lbfgsb options: 2 2
_prepare_scalar_function
C
D
F
init
update_fun: <function ScalarFunction.__init__.<locals>.update_fun at 0x3170d3880>
fun_wrapped
args: ()
FD_METHODS
finite_diff_options: {'method': '2-point', 'rel_step': None, 'abs_step': 1e-08, 'bounds': (array([-inf, -inf, -inf, ..., -inf, -inf, -inf]), array([inf, inf, inf, ..., inf, inf, inf]))}
Help on function update_grad in module scipy.optimize._differentiable_functions:

update_grad()

update_grad: None
not self.g_updated
approx deriv
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_wrapped
args: ()
fun_

KeyboardInterrupt: 

In [ ]:
scipy.optimize

<module 'scipy.optimize' from '/opt/homebrew/Caskroom/miniforge/base/envs/proj_2_env/lib/python3.12/site-packages/scipy/optimize/__init__.py'>

In [ ]:
len(set(torch.wherae(torch.eq(data_copy.x, data.x)==False)[1].tolist()))

767

In [ ]:
data.x[24,0]

tensor(0.)

In [ ]:
data_copy.x[[24,25],[0,1]]

tensor([-4.8543e-05,  0.0000e+00])

In [ ]:
import torch

t = torch.tensor([1,12])
t.numpy()

array([ 1, 12])

In [ ]:
def get_beta_weights(subgraph_dict, num_features):
    if config.watermark_loss_kwargs['balance_beta_weights'] == True:
        beta_weights = get_balanced_beta_weights([subgraph_dict[sig]['subgraph'] for sig in subgraph_dict.keys()])
    elif config.watermark_loss_kwargs['balance_beta_weights'] == False:
        beta_weights = torch.ones(len(subgraph_dict),num_features)
    return beta_weights

def process_beta(beta, alpha, omit_indices, scale_beta_method='clip'):
    if scale_beta_method=='tanh':
        beta = torch.tanh(alpha*beta)
    elif scale_beta_method=='tan':
        beta = torch.tan(alpha*beta)
    elif scale_beta_method=='clip':
        beta = torch.clip(beta,min=-1,max=1)
    elif scale_beta_method==None:
        pass
    beta = beta.clone()  # Avoid in-place operation
    if omit_indices is not None and len(omit_indices)>0:
        beta[omit_indices] = 0 # zero out non-contributing indices
    return beta

def compute_watermark_loss(subgraph_dict, probas, beta_weights):
    watermark_loss_kwargs = config.watermark_loss_kwargs
    regression_kwargs = config.regression_kwargs
    optimization_kwargs = config.optimization_kwargs

    loss_watermark = torch.tensor(0.0)
    for s, sig in enumerate(subgraph_dict.keys()):
        this_watermark, data_sub, subgraph_node_indices = [subgraph_dict[sig][k] for k in ['watermark','subgraph','nodeIndices']]
        x_sub, y_sub = data_sub.x, probas[subgraph_node_indices]
        ''' epoch condtion: epoch==epoch-1'''
        omit_indices,not_omit_indices = get_omit_indices(x_sub, this_watermark,ignore_zeros_from_subgraphs=False) #indices where watermark is 0
        raw_beta            = solve_regression(x_sub, y_sub, regression_kwargs['lambda'])
        beta                = process_beta(raw_beta, watermark_loss_kwargs['alpha'], omit_indices, watermark_loss_kwargs['scale_beta_method'])
        B_x_W = (beta*this_watermark).clone()
        B_x_W = B_x_W[not_omit_indices]

        balanced_beta_weights = beta_weights[s]
        balanced_beta_weights = balanced_beta_weights[not_omit_indices]
        loss_watermark = loss_watermark+torch.mean(torch.clamp(watermark_loss_kwargs['epsilon']-B_x_W, min=0)*balanced_beta_weights)


    loss_watermark = loss_watermark/len(subgraph_dict)
    loss_watermark_scaled = loss_watermark*optimization_kwargs['coefWmk']
    return loss_watermark_scaled


beta_weights = get_beta_weights(subgraph_dict, data.x.shape[1])
all_subgraph_indices = []
for sig in subgraph_dict.keys():
    nodeIndices = subgraph_dict[sig]['nodeIndices']
    all_subgraph_indices+=nodeIndices.tolist()
reg_copy=None


lr = 0.002
optimizer = optim.Adam(node_classifier.parameters(), lr=lr)


for j in range(100):
    x_copy,edge_index_copy = copy.deepcopy(data).x, copy.deepcopy(data).edge_index
    x_copy = x_copy.requires_grad_(True)
    #with torch.no_grad():
    #    edge_index_copy, x_copy, _ = augment_data(data, node_aug, edge_aug, train_nodes_to_consider, all_subgraph_indices)
    #    x_copy = x_copy.requires_grad_(True)
    log_logits_copy          = node_classifier(x_copy, edge_index_copy)
    probas_copy = log_logits_copy.clone().exp()
    loss_watermark_scaled_copy = compute_watermark_loss(subgraph_dict, probas_copy, beta_weights)
    wmk_loss = loss_watermark_scaled_copy+reg_copy if reg_copy is not None else loss_watermark_scaled_copy
    optimizer.zero_grad()
    wmk_loss.backward()
    print(f'{j}/20: {wmk_loss:3f}',end='\r')
    this_grad = torch.zeros_like(data.x)
    this_grad[all_subgraph_indices] = x_copy.grad.clone()[all_subgraph_indices]
    this_grad[all_subgraph_indices] = (this_grad[all_subgraph_indices]-this_grad[all_subgraph_indices].mean())/(this_grad[all_subgraph_indices].max()-this_grad[all_subgraph_indices].min())
    x_grad_wmk_loss = torch.zeros_like(data.x)
    x_grad_wmk_loss[all_subgraph_indices] = this_grad.clone()[all_subgraph_indices]
    # print(x_grad_wmk_loss[all_subgraph_indices])
    data.x = data.x - perturb_lr*x_grad_wmk_loss
    optimizer.zero_grad()

KeyboardInterrupt: 

In [ ]:
beta_weights = get_beta_weights(subgraph_dict, data.x.shape[1])
for s, sig in enumerate(subgraph_dict.keys()):
    this_watermark, data_sub, subgraph_node_indices = [subgraph_dict[sig][k] for k in ['watermark','subgraph','nodeIndices']]
    x_sub, y_sub = data_sub.x, probas[subgraph_node_indices]
    ''' epoch condtion: epoch==epoch-1'''
    omit_indices,not_omit_indices = get_omit_indices(x_sub, this_watermark,ignore_zeros_from_subgraphs=False) #indices where watermark is 0
    print(not_omit_indices)

tensor([  7,  11,  23,  34,  37,  41,  43,  69,  73,  86,  97, 105, 109, 110,
        134, 144, 154, 159, 168, 177, 185, 186, 195, 212, 217, 219, 225, 227,
        238, 250, 259, 277, 279, 284, 298, 328, 355, 358, 363, 365, 367, 376,
        382, 386, 427, 430, 439, 442, 443, 457, 489, 503, 506, 507, 515, 520,
        542, 544, 554, 559, 582, 597, 617, 649, 664, 687, 695, 698, 704, 708,
        715, 729, 732, 747, 755, 758])


In [ ]:
subgraph_dict.keys()

dict_keys(['11293_4896_5573_3951_10751_63'])